### ISSUE TITLE
PublicRoute does not depend on gateway attachment

### ISSUE THREAD

**Issue by clareliguori** [awslabs/aws-cdk#1140]
Got the following error when deploying ec2.VpcNetwork: `route table rtb-xxxx and network gateway igw-yyyy belong to different networks`.  This appears to be a race condition when the gateway attachment has not yet completed by the time the public route is created.  The PublicRoute needs to depend on the gateway attachment:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html#gatewayattachment

Example synthesized route:
```
  VPCPublicSubnet2DefaultRouteB7481BBA:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId:
        Ref: VPCPublicSubnet2RouteTable6F1A15F1
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: VPCIGWB7E252D3
```
Route element needs a "DependsOn" for the gateway attachment
