### ISSUE TITLE
cloudwatch alarms: how to add alarm dependency?

### ISSUE THREAD

**Issue by clareliguori** [awslabs/aws-cdk#1213]
Version: 0.18.0

I'm running into a dependency issue creating an alarm: the alarm dimensions indirectly refer to a target group and load balancer that have not yet been created during stack creation.  How do I add a dependency on these objects?  There doesn't seem to be a way to add the equivalent of "DependsOn" to a construct.

Code:
```
   new Alarm(this, 'TargetGroupUnhealthyHosts', {
      metric: service.targetGroup.metricUnhealthyHostCount(),
      threshold: 1,
      evaluationPeriods: 2,
    });
```

Error:
```
Template error: Fn::Select  cannot select nonexistent value at index 0
```

Generated snippet:
```
      Dimensions:
        - Name: TargetGroup
          Value:
            'Fn::GetAtt':
              - ServiceLBPublicListenerECSGroup0CC8688C
              - TargetGroupFullName
        - Name: LoadBalancer
          Value:
            'Fn::Join':
              - ''
              - - 'Fn::Select':
                    - 1
                    - 'Fn::Split':
                        - /
                        - 'Fn::Select':
                            - 0
                            - 'Fn::GetAtt':
                                - ServiceLBPublicListenerECSGroup0CC8688C
                                - LoadBalancerArns
                - /
                - 'Fn::Select':
                    - 2
                    - 'Fn::Split':
                        - /
                        - 'Fn::Select':
                            - 0
                            - 'Fn::GetAtt':
                                - ServiceLBPublicListenerECSGroup0CC8688C
                                - LoadBalancerArns
                - /
                - 'Fn::Select':
                    - 3
                    - 'Fn::Split':
                        - /
                        - 'Fn::Select':
                            - 0
                            - 'Fn::GetAtt':
                                - ServiceLBPublicListenerECSGroup0CC8688C
                                - LoadBalancerArns
```
