### ISSUE TITLE
When creating a security group, allowAllOutbound parameter seems to be ignored

### ISSUE THREAD

**Issue by dpllpd** [awslabs/aws-cdk#1430]
When I create a security group and specify allowAllOutbound=false, a security group with the default egress rule that allows all ports is created anyway. It is called ....InstanceSecurityGroup.... I can't find a way to change that. 

const securityGroup = new ec2.SecurityGroup(parent, 'SecurityGroup', {
            vpc,
            description: 'xxxx',
            allowAllOutbound: false
        });

**Comment by RomainMuller** [comment]
Attempted to reproduce the issue with the following:
```ts
import ec2 = require('@aws-cdk/aws-ec2')
import cdk = require('@aws-cdk/cdk');

export class ReproStack extends cdk.Stack {
  constructor(parent: cdk.App, name: string, props?: cdk.StackProps) {
    super(parent, name, props);

    const vpc = new ec2.VpcNetwork(this, 'VPC', {
      maxAZs: 1
    });
    new ec2.SecurityGroup(this, 'SG', {
      allowAllOutbound: false,
      description: '#1340',
      vpc,
    });
  }
}
```

This yielded the security group as I expected it:
```yaml
  SGADB53937:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "#1340"
      SecurityGroupEgress:
        - CidrIp: 255.255.255.255/32
          Description: Disallow all traffic
          FromPort: 252
          IpProtocol: icmp
          ToPort: 86
      SecurityGroupIngress:
        []
      VpcId:
        Ref: VPCB9E5F0B4
    Metadata:
      aws:cdk:path: ReproStack/SG/Resource
```

It would help if you can elaborate with a minimal reproduction for your issue (the code, what it yields, and what you expected it to yield).
