### ISSUE TITLE
creationPolicy type does not support Tokens

### ISSUE THREAD

**Issue by mipearson** [awslabs/aws-cdk#1453]
Trying to convert the following to CDK-flavoured L2 constructs:

```yaml
    CreationPolicy:
      ResourceSignal:
        Timeout: !Ref InstanceCreationTimeout
        Count: !Ref MinSize
```

However, the CDK types do not seem to support using anything other than a number. The following fails typescript compilation:

```typescript
    autoscaler.options.creationPolicy = {
      resourceSignal: {
        timeout: new cdk.Token(instanceCreationTimeout.ref),
        count: new cdk.Token(minSize.ref)
      }
    };
```

The `resourceSignal` type only accepts `number` and `undefined` for `count`, meaning I can't "cheat" and use a stringified nor a raw token.

Note that this is using CDK in its context as a "way to write cloudformation templates" rather than the entire app, so parameters / outputs / conditionals are being used.
