### ISSUE TITLE
Expect FargateTaskDefinition.addContainer() to automatically update the overall task CPU and Memory

### ISSUE THREAD

**Issue by nathanpeck** [awslabs/aws-cdk#1553]
The Fargate task definition does not update from its default CPU reservation of 256 and memory reservation of 512 as expected:

```js
    const taxiDataLoader = new ecs.FargateTaskDefinition(this, 'nyc-taxi-loader-definition', {});

    taxiDataLoader.addContainer('nyc-taxi-loader', {
      image: ecs.ContainerImage.fromAsset(this, 'nyc-taxi-loader-container', { directory: './nyc-taxi-loader' }),
      memoryMiB: 2048,
      cpu: 1024,
      logging: new ecs.AwsLogDriver(this, 'nyc-taxi-loader-logs', {
        streamPrefix: 'nyc-taxi-loader'
      })
    });
```

My expectation is that the task definition will automatically have its CPU and memory set based on the values that I specified for the single container that is inside the task. Instead after running `cdk deploy` the CloudFormation deploy fails with error:

```
The sum of all container 'cpu' values cannot be greater than the value of the task 'cpu'. (Service: AmazonECS; Status Code: 400; Error Code: ClientException;
```

`cdk synth` shows that the synthesized task definition CloudFormation kept the default values of `256` for CPU and `512` for memory instead of picking up the increased cpu and memory from my container:

```yaml
nyctaxiloaderdefinitionA8697DA8:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Cpu: 1024
          Essential: true
          Image:
            Fn::Join:
              - ""
              - - Fn::Select:
                    - 4
                    - Fn::Split:
                        - ":"
                        - Fn::Join:
                            - ""
                            - - "arn:"
                              - Ref: AWS::Partition
                              - ":ecr:"
                              - Ref: AWS::Region
                              - ":"
                              - Ref: AWS::AccountId
                              - :repository/
                              - Fn::GetAtt:
                                  - nyctaxiloadercontainerAdoptRepository213ABCEE
                                  - RepositoryName
                - .dkr.ecr.
                - Fn::Select:
                    - 3
                    - Fn::Split:
                        - ":"
                        - Fn::Join:
                            - ""
                            - - "arn:"
                              - Ref: AWS::Partition
                              - ":ecr:"
                              - Ref: AWS::Region
                              - ":"
                              - Ref: AWS::AccountId
                              - :repository/
                              - Fn::GetAtt:
                                  - nyctaxiloadercontainerAdoptRepository213ABCEE
                                  - RepositoryName
                - .amazonaws.com/
                - Fn::GetAtt:
                    - nyctaxiloadercontainerAdoptRepository213ABCEE
                    - RepositoryName
                - ":"
                - Fn::Select:
                    - 1
                    - Fn::Split:
                        - ":"
                        - Ref: nyctaxiloadercontainerImageNameDFEC0A8B
          Links:
            []
          LinuxParameters:
            Capabilities:
              Add:
                []
              Drop:
                []
            Devices:
              []
            Tmpfs:
              []
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: nyctaxiloaderlogsLogGroupDD1C002E
              awslogs-stream-prefix: nyc-taxi-loader
              awslogs-region:
                Ref: AWS::Region
          MountPoints:
            []
          Name: nyc-taxi-loader
          PortMappings:
            []
          Ulimits:
            []
          VolumesFrom:
            []
      Cpu: "256"
      ExecutionRoleArn:
        Fn::GetAtt:
          - nyctaxiloaderdefinitionExecutionRole958A3861
          - Arn
      Family: nyctaxiloadernyctaxiloaderdefinition35B017F8
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn:
        Fn::GetAtt:
          - nyctaxiloaderdefinitionTaskRoleBC1C04E9
          - Arn
      Volumes:
        []
    Metadata:
      aws:cdk:path: nyc-taxi-loader/nyc-taxi-loader-definition/Resource
```

My expectation is that the `FargateTaskDefinition` construct should automatically sum up the CPU and memory reservation of each container added via `addContainer()` and set the overall task CPU and memory to the closest deployable Fargate task size that has room to run all the added containers
