### ISSUE TITLE
[aws-codepipeline] Parameter overrides cannot use Fn::GetArtifactAtt

### ISSUE THREAD

**Issue by piotrkubisa** [awslabs/aws-cdk#1588]
I have been trying to create a deployment pipeline for Lambda function using CodePipeline. During development I noticed there is weird issue which does not allow me to use `Fn::GetArtifactAtt` in the `parameterOverrides` (1), because default JSON serializer forces to use `Fn::Join` which does not accept `Fn::GetArtifactAtt`.

(1): https://github.com/awslabs/aws-cdk/blob/4af7c0d97b17820a41ef9d611ed6768f62d64a6c/packages/%40aws-cdk/aws-cloudformation/lib/pipeline-actions.ts#L189

I see it was noticed in #566, but for `0.22.0 (build 644ebf5)` version it does not work for me.

```ts
import iam = require('@aws-cdk/aws-iam');
import codepipeline = require('@aws-cdk/aws-codepipeline');
import cloudformation = require('@aws-cdk/aws-cloudformation');
import codepipelineapi = require('@aws-cdk/aws-codepipeline-api');

const addDeployPrepareAction = (
    id: string,
    buildArtifact:  codepipelineapi.Artifact,
    props: {
        stage: codepipeline.Stage,
        stackName: string,
        region: string,
        changeSetName: string,
        role: iam.Role
    }
) => {
    const { stackName, stage, region, changeSetName, role } = props

    new cloudformation.PipelineCreateReplaceChangeSetAction(stage, id, {
        stackName,
        stage,
        region,
        role,
        changeSetName,
        runOrder: 1,
        adminPermissions: false,
        capabilities: cloudformation.CloudFormationCapabilities.NamedIAM,
        parameterOverrides: {
            'LambdaCodeZip': buildArtifact.objectKey,
            'LambdaCodeBucket': buildArtifact.bucketName,
        },
    })
}
```

Expected (one of the possible solution):

```yaml
ParameterOverrides: !Sub |
  {
    "LambdaCodeZip" : { "Fn::GetArtifactAtt" : [ "BuildOutput", "ObjectKey" ] },
    "LambdaCodeBucket": { "Fn::GetArtifactAtt" : [ "BuildOutput", "BucketName" ] }
  }
```

Actual:

```yaml
ParameterOverrides:
  Fn::Join:
    - ""
    - - '{"LambdaCodeZip":"'
      - Fn::GetArtifactAtt:
          - BuildOutput
          - ObjectKey
      - '","LambdaCodeBucket":"'
      - Fn::GetArtifactAtt:
          - BuildOutput
          - BucketName
      - '"}'
```

Error:

```console
aws cloudformation validate-template --template-body file://pipeline.json

An error occurred (ValidationError) when calling the ValidateTemplate operation: Template Error: Encountered unsupported function: Fn::GetArtifactAtt Supported functions are: [Fn::Base64, Fn::GetAtt, Fn::GetAZs, Fn::ImportValue, Fn::Join, Fn::Split, Fn::FindInMap, Fn::Select, Ref, Fn::Equals, Fn::If, Fn::Not, Condition, Fn::And, Fn::Or, Fn::Contains, Fn::EachMemberEquals, Fn::EachMemberIn, Fn::ValueOf, Fn::ValueOfAll, Fn::RefAll, Fn::Sub, Fn::Cidr]
```

**Comment by rix0rrr** [comment]
The problem here seems to be that `{Fn::GetArtifactAtt}` is modeled as an actual CloudFormation intrinsic, whereas it's supposed to be just opaque JSON in the `ParameterOverrides` property?

> Expected (one of the possible solution):
> ParameterOverrides: !Sub |

What does the `!Sub` still add here? Does it do anything?

**Comment by rix0rrr** [comment]
cc @skinny85

**Comment by piotrkubisa** [comment]
> The problem here seems to be that `{Fn::GetArtifactAtt}` is modeled as an actual CloudFormation intrinsic, whereas it's supposed to be just opaque JSON in the `ParameterOverrides` property?

No, it is not a problem that `Fn::GetArtifactAtt` is used as an actual instrict function - it is an expected behavior. I guess I will encounter the same problem with `Fn::GetParam` in `ParameterOverrides`. Please read more about these two dedicated function: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-parameter-override-functions.html

> > Expected (one of the possible solution):
> > ParameterOverrides: !Sub |
> 
> What does the `!Sub` still add here? Does it do anything?

* It takes care of creating a valid JSON object - adds braces - `{` and `}`
* I stripped few more parameters in that example which does not relate directly to the issue, here is an example how you might use `Fn::Sub` with some `Parameter` or using any other function (`Fn::GetAtt`, `Fn::Ref`...)

```yaml
ParameterOverrides: !Sub |
  {
    "LambdaCodeZip" : { "Fn::GetArtifactAtt" : [ "LambdaHandlerOutput", "ObjectKey" ] },
    "LambdaCodeBucket": { "Fn::GetArtifactAtt" : [ "LambdaHandlerOutput", "BucketName" ] },
    "AssetsBucketName": "${AssetsBucket}",
    "AssetsBucketDomainName": "${AssetsBucket.DomainName}",
    "GitHubRepositoryName": "${GitHubRepositoryName}"
  }
```

For an example I provided in first post **!Sub is not required to work**, but you have to keep the `|` pipe character to inform you are starting a multi-line block.

YAML:

```yaml
ParameterOverrides: |
  {
    "LambdaCodeZip" : { "Fn::GetArtifactAtt" : [ "BuildOutput", "ObjectKey" ] },
    "LambdaCodeBucket": { "Fn::GetArtifactAtt" : [ "BuildOutput", "BucketName" ] }
  }
```

JSON:

```json
{
  "ParameterOverrides": "{\n  \"LambdaCodeZip\" : { \"Fn::GetArtifactAtt\" : [ \"BuildOutput\", \"ObjectKey\" ] },\n  \"LambdaCodeBucket\": { \"Fn::GetArtifactAtt\" : [ \"BuildOutput\", \"BucketName\" ] }\n}\n",
}
```

**Comment by piotrkubisa** [comment]
> For an example I provided in first post !Sub is not required to work, but you have to keep the | pipe character to inform you are starting a multi-line block.

// It is not required, but it is better to have it, because `Fn::Sub` rocks and `Fn:Join` sucks! :stuck_out_tongue:

**Comment by piotrkubisa** [comment]
As a workaround we may mock it in following way:

```ts
  parameterOverrides: {
    'LambdaCodeZip': `{ "Fn::GetArtifactAtt" : [ "${buildArtifact.name}", "ObjectKey" ] }`,
    'LambdaCodeBucket': `{ "Fn::GetArtifactAtt" : [ "${buildArtifact.name}", "BucketName" ] }`,
    'GitHubRepositoryName': cdk.Fn.sub('${GitHubRepositoryName}'),
  },
```

Output YAML:

```yaml
ParameterOverrides:
  Fn::Join:
    - ""
    - - '{"LambdaCodeZip":"{ \"Fn::GetArtifactAtt\" : [
        \"LambdaHandlerOutput\", \"ObjectKey\" ]
        }","LambdaCodeBucket":"{ \"Fn::GetArtifactAtt\" : [
        \"LambdaHandlerOutput\", \"BucketName\" ] }","Stage":"'
      - Fn::Sub: ${Stage}
      - '","GitHubRepositoryName":"'
      - Fn::Sub: ${GitHubRepositoryName}
      - '"}'
```

Output JSON:

```json
{
  "ParameterOverrides": {
    "Fn::Join": [
      "",
      [
        "{\"LambdaCodeZip\":\"{ \\\"Fn::GetArtifactAtt\\\" : [ \\\"LambdaHandlerOutput\\\", \\\"ObjectKey\\\" ] }\",\"LambdaCodeBucket\":\"{ \\\"Fn::GetArtifactAtt\\\" : [ \\\"LambdaHandlerOutput\\\", \\\"BucketName\\\" ] }\",\"Stage\":\"",
        {
          "Fn::Sub": "${Stage}"
        },
        "\",\"GitHubRepositoryName\":\"",
        {
          "Fn::Sub": "${GitHubRepositoryName}"
        },
        "\"}"
      ]
    ]
  }
}
```

**Comment by skinny85** [comment]
@piotrkubisa thanks for reporting this one, I'm looking into it.

Quick question: did your workaround from [this comment](https://github.com/awslabs/aws-cdk/issues/1588#issuecomment-456362115) work? I does deploy through CFN, however the Pipeline with those `Parameter Overrides` set fails updating its Stack for me,  because of escaping (CFN thinks `{ "Fn::GetArtifactAtt" : [ "BuildOutput", "BucketName" ]` is literally the Bucket name).

**Comment by piotrkubisa** [comment]
Sadly, no it does not work :cry: You are right it will provide `{ "Fn::GetArtifactAtt" : [ "BuildOutput", "BucketName" ] }` as a string value as a parameter.

**Comment by skinny85** [comment]
I figured out what the issue is. I submitted a PR with the fix [here](https://github.com/awslabs/aws-cdk/pull/1605).

**Comment by piotrkubisa** [comment]
Thanks!

**Comment by skinny85** [comment]
NP, thanks for reporting the issue!

**Comment by rebolyte** [comment]
This seems to be still be happening when not used in the Cfn `parameterOverrides` property. Given this:

```ts
new PipelineProject(scope, `Project`, {
	// ...
	environmentVariables: {
		WEB_API_LOC: {
			type: BuildEnvironmentVariableType.PLAINTEXT,
			value: JSON.stringify(props.webApiLambdaCode.assign(webApiOutput.s3Location))
		}
	}
	// ...
})
```

You still get this output:

```yaml
ProjectD3596EDB:
  Type: AWS::CodeBuild::Project
  Properties:
    Artifacts:
      Type: CODEPIPELINE
    Environment:
      ComputeType: BUILD_GENERAL1_SMALL
      EnvironmentVariables:
        - Name: WEB_API_LOC
          Type: PLAINTEXT
          Value:
            Fn::Join:
              - ""
              - - '{"ApiApiFuncLambdaSourceBucketNameParameterB6671E0E":"'
                - Fn::GetArtifactAtt:
                    - WebApiOut
                    - BucketName
                - '","ApiApiFuncLambdaSourceObjectKeyParameter1B2544EC":"'
                - Fn::GetArtifactAtt:
                    - WebApiOut
                    - ObjectKey
                - '"}'
```
