### ISSUE TITLE
How to specify DeletionPolicy to Delete?

### ISSUE THREAD

**Issue by piotrkubisa** [awslabs/aws-cdk#1637]
I don't see any non-hacky* way to define `DeletionPolicy` with a `Delete` as a value. In `cdk` I noticed there is a `cdk.applyRemovalPolicy` function which does have `cdk.RemovalPolicy.Destroy`, which on first glance I thought it attaches that removal policy but no, it does not. 

Stack definition:

```ts
import s3 = require('@aws-cdk/aws-s3')
import cdk = require('@aws-cdk/cdk')

export class SomeStack extends cdk.Stack {
  protected PrefixName: cdk.Parameter
  protected BucketName: cdk.Parameter

  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props)

    this.addResources()
  }

  public addResources() {
    const bucket = new s3.CfnBucket(this, 'ArtifactBucket', {
      bucketName: 'hello-world',
    })
    cdk.applyRemovalPolicy(bucket, cdk.RemovalPolicy.Destroy)
  }
}
```

Synthesized:

```yml
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hello-world
    Metadata:
      aws:cdk:path: some-stack/ArtifactBucket
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.22.0...
```

Expected:

```yml
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "hello-world"
    DeletionPolicy: Delete
```

// * workaround:

```ts
bucket.addOverride('DeletionPolicy', 'Delete')
```
