### ISSUE TITLE
Unable to set child tags when parent tags are inherited

### ISSUE THREAD

**Issue by cbeattie-bsm** [awslabs/aws-cdk#1725]
It seems when you apply tags at a parent scope, any additional tags set on a child will not be set.

```
class MyParentConstruct extends cdk.Construct {
  constructor(scope: cdk.Construct, id: string) {
    super(scope, id);

    this.apply(new cdk.Tag('Foo', 'Bar'));

    new MyChildConstruct(this, 'Child');
  }
}

class MyChildConstruct extends cdk.Construct {
  constructor(scope: cdk.Construct, id: string) {
    super(scope, id);

    new cdkEc2.CfnVPC(this, 'Vpc', {
      cidrBlock: '10.0.0.0/16',
      tags: [
        {key: 'Name', value: 'MyVPC'},
      ]
    });
  }
}
```

Results:
```
Resources:
  testChildVpc5FFB6B5B:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Foo
          Value: Bar
    Metadata:
      aws:cdk:path: PartitionStack/test/Child/Vpc
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.24.1,@aws-cdk/aws-cloudwatch=0.24.1,@aws-cdk/aws-ec2=0.24.1,@aws-cdk/aws-iam=0.24.1,@aws-cdk/aws-logs=0.24.1,@aws-cdk/cdk=0.24.1,@aws-cdk/cx-api=0.24.1,jsii-runtime=node.js/v8.11.3
```

I would expect that the child object would have both a 'Foo' and 'Name' tag.
