### ISSUE TITLE
CDKMetadata: aws-cdk not updated

### ISSUE THREAD

**Issue by spg** [awslabs/aws-cdk#1910]
I updated my CloudFormatinon stack from cdk 0.24.1 to 0.25.0 this morning.
After running `cdp deploy`, the `aws-cdk` version in the stack's metadata seems to be wrong:
```
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.22.0,@aws-cdk/aws-cloudwatch=0.25.0,@aws-cdk/aws-iam=0.25.0,@aws-cdk/cdk=0.25.0,@aws-cdk/cx-api=0.25.0,jsii-runtime=node.js/v11.6.0
```
Notice how `aws-cdk=0.22.0` while all other versions are updated to `0.25.0`.

Not sure if this is a bug or a feature.
