### ISSUE TITLE
[Feature] ecs.FargateService should accept array of subnets

### ISSUE THREAD

**Issue by robertd** [awslabs/aws-cdk#1951]
It would be nice if we can pass existing subnets to a [FargateServiceProps](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-ecs.html#@aws-cdk/aws-ecs.FargateServiceProps). Our SecOps prevents us from creating subnets ad-hoc, thus we cannot use `ecs.FargateService` construct. Thanks!

```
const service = new ecs.FargateService(this, "FargateService", {
    cluster: cluster,
    taskDefinition: fargateTaskDefinition,
    desiredCount: 1,
    securityGroup: sg
});
```

**Comment by rix0rrr** [comment]
You can `import` an existing VPC network (see `ec2.VpcNetwork.importFromContext`).

The Fargate Service will use the private subnets from the imported VPC network. Should you need the public subnets, you pass the `vpcPlacement` property.

**Comment by allankp** [comment]
Need a bit of guidance on a related issue. Subnets for my fargate service are never populated

```
  networkConfiguration:
   { awsvpcConfiguration:
      { assignPublicIp: 'DISABLED',
        subnets: [],
        securityGroups: [Token] } } }
```


```        const vpc = ec2.VpcNetwork.import(this, 'vpc', {
            vpcId: 'vpc-925937f4',
            availabilityZones: ['eu-west-1a', 'eu-west-1b'],
            privateSubnetIds: ['subnet-ea78xxxx', 'subnet-f73cxxxx'],
        });

        const cluster = ecs.Cluster.import(this, 'Cluster', {
            clusterName: "cluster_name",
            vpc: vpc,
            securityGroups: [{securityGroupId: 'securityGroupId'}]
        })

        const fargateService = new ecs.FargateService(this, 'FargateService', {
            cluster: cluser,
            taskDefinition: taskname
            desiredCount: 2,
        });
```

**Comment by rix0rrr** [comment]
@allankp `Cluster.import` does not take an `IVpcNetwork`, it takes `VpcNetworkImportProps`. Correct code:

```ts
 const cluster = ecs.Cluster.import(this, 'Cluster', {
            clusterName: "cluster_name",
            vpc: {
              vpcId: 'vpc-xxxxx',
              availabilityZones: ['eu-west-1a', 'eu-west-1b'],
              privateSubnetIds: ['subnet-xxxxx', 'subnet-xxxx'],
            },
            securityGroups: [{securityGroupId: 'securityGroupId'}]
        })
```

**Comment by allankp** [comment]
@rix0rrr Rookie mistake, much appreciated

**Comment by robertd** [comment]
@rix0rrr Thank you for clarifying that.  Originally, I've used imported vpc (via `importFromContext`) and passed it down to cluster. I was surprised that cluster/VSCode didn't yell at me (see screenshot attached).  

![image](https://user-images.githubusercontent.com/31543/53817860-e59a2300-3f23-11e9-8268-304803c423c0.png)

But anyway, after your last reply to @allankp I've changed things around 

```
    //Import existing Security Group
     const sg = ec2.SecurityGroup.import(this, "SecurityGroup", {
      securityGroupId: props.securityGroupId
    });

    const cluster = ecs.Cluster.import(this, "Cluster", {
      clusterName: props.clusterName,
      securityGroups: [ sg ],
      vpc: {
        vpcId: props.vpcId,
          availabilityZones: ['us-west-2'],
          privateSubnetIds: subnets       
      }
    });
```
... and my CFN looks like this

```
...
  ServiceD69D759B:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition:
        Ref: TaskDefinitionB36D86D9
      Cluster: DlvAPPEcsClustersStack-AppF1B96344-5WK03WOT8LSV
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DesiredCount: 1
      LaunchType: FARGATE
      LoadBalancers: []
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - sg-xxxxxxx
          Subnets:
            - subnet-xxxxxxx
            - subnet-xxxxxxx
            - subnet-xxxxxxx
...
```

TY!
