### ISSUE TITLE
IAM PolicyPrincipal should accept references

### ISSUE THREAD

**Issue by rli** [awslabs/aws-cdk#2164]
It should be possible to replicate this Cloudformation with CDK:

```yaml
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                - !Ref ToolsAccount
            Action:
              - sts:AssumeRole
```

Current workaround:

```ts
        this.toolsAccount = new cdk.Parameter(this, 'ToolsAccount', {
            type: 'String',
            default: '123456789012'
        });
       ...
        new iam.Role(this, 'some-role', {
            assumedBy: new iam.ArnPrincipal(this.toolsAccount.ref),
        })
```
