### ISSUE TITLE
ecr: grant methods cause circular references in generated templates

### ISSUE THREAD

**Issue by otterley** [awslabs/aws-cdk#2473]
The `grant*` methods on the ecr.Repository class incorrectly add self-references to the repository's policies, leading to a circular reference error.

Example code:

```typescript
const repo = new ecr.Repository(this, 'TestHarnessRepo', {
    repositoryName: props.repoName,
});
repo.grantPull(principal);
```

Rendered template (in relevant part):

```
TestHarnessRepoAA7E9724:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: codebuild-inspec-test-harness
      RepositoryPolicyText:
        Statement:
          - Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - codebuild.
                    - Ref: AWS::URLSuffix
            Resource:
              Fn::GetAtt:
                - TestHarnessRepoAA7E9724 # !!!! this is the problem
                - Arn
```

ECR repository policies do not require resources to be defined (or they can be set to `*`) -- see [the documentation](https://docs.aws.amazon.com/AmazonECR/latest/userguide/RepositoryPolicyExamples.html) for examples.
