### ISSUE TITLE
Invalid template when using cross-region pipeline actions

### ISSUE THREAD

**Issue by ghidi** [awslabs/aws-cdk#2575]
**Describe the bug**
When using cross-region pipeline actions, CDK generates a template that has invalid properties (ArtifactStores.ArtifactStore.EncryptionKey.**type** and **id** are lowercase). 

```
cdk deploy PipelineStack-us-west-2
PipelineStack-us-west-2: deploying...
PipelineStack-us-west-2: creating CloudFormation changeset...
 1/2 | 9:47:57 AM | UPDATE_FAILED        | AWS::CodePipeline::Pipeline | NexusComponents (NexusComponents5E6B9324) Encountered unsupported property type
	new Pipeline (/Users/bogdang/Work/brazil/nexus-2-ws/src/NexusBatchInfra/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.js:83:30)
	\_ new PipelineStack (/Users/bogdang/Work/brazil/nexus-2-ws/src/NexusBatchInfra/lib/nexus-pipeline.js:75:9)
	\_ Object.<anonymous> (/Users/bogdang/Work/brazil/nexus-2-ws/src/NexusBatchInfra/bin/nexus-infra.js:30:1)
	\_ Module._compile (internal/modules/cjs/loader.js:759:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
	\_ Module.load (internal/modules/cjs/loader.js:628:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:555:12)
	\_ Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
	\_ internal/main/run_main_module.js:17:11

```
This is caused by: 
```
ArtifactStores:
  - Region: us-west-2
    ArtifactStore:
      Location:
        Ref: NexusComponentsArtifactsBucketE32AB8F7
      Type: S3
      EncryptionKey:
        type: KMS --> (should be Type)
        id: --> (should be Id)
          Fn::GetAtt:
            - NexusComponentsArtifactsBucketEncryptionKeyC41073DC
            - Arn

```
If I synthesize the template, change **type** to **Type**, **id** to **Id** and deploy it directly from the console, it works.

**To Reproduce**
Create a pipeline that has cross-region deploy CloudFormation actions.

**Version:**
 - Programming Language TypeScript
 - CDK Version 0.31.0
