### ISSUE TITLE
addPropertyOverride() does not seem to work

### ISSUE THREAD

**Issue by spg** [awslabs/aws-cdk#2677]
**Describe the bug**
`addPropertyOverride` does not seem to work

**To Reproduce**
Synthetize the following stack:

```
import cdk = require('@aws-cdk/cdk');
import s3 = require('@aws-cdk/aws-s3');


export class TestStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const bucket = new s3.Bucket(this, 'MyBucket');
    const bucketResource = bucket.node.findChild('Resource') as s3.CfnBucket;
    bucketResource.addPropertyOverride('AccessControl', 'bucket-owner-read');
  }
}
```

yields the following:

```
npx cdk synth test-stack
Resources:
  MyBucketF68F3FF0:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: test-stack/MyBucket/Resource
    Properties: {}
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.32.0,@aws-cdk/aws-events=0.32.0,@aws-cdk/aws-iam=0.32.0,@aws-cdk/aws-kms=0.32.0,@aws-cdk/aws-s3=0.32.0,@aws-cdk/aws-s3-notifications=0.32.0,@aws-cdk/cdk=0.32.0,@aws-cdk/cx-api=0.32.0,@aws-cdk/region-info=0.32.0,jsii-runtime=node.js/v11.6.0
```

Note that `AccessControl` is absent from the synth output.

**Expected behavior**
`AccessControl: "bucket-owner-read"` should be seen in the synth output

**Version:**
 - OS: OS X 10.14.5
 - Programming Language: Typescript
 - CDK Version: 0.32.0
