### ISSUE TITLE
Mutation of string references of runtime attributes not preserved 

### ISSUE THREAD

**Issue by kevinslin** [awslabs/aws-cdk#2718]
**Describe the bug**

When I use javascript functions to manipulate the string reference of the ARN of an ALB created via CDK, the changes don't get synthesized into the resulting template (resolves to a reference to the original ALB instead). 

**To Reproduce**
- code
```ts
import elbv2 = require('@aws-cdk/aws-elasticloadbalancingv2');
import cw = require('@aws-cdk/aws-cloudwatch');

const lb = new elbv2.ApplicationLoadBalancer(scope, `lb`, {lbProps})
/*
The LoadBalancer dimension in cloudwatch for ALB is the second half of the ALB ARN
- ALB ARN: arn:aws:elasticloadbalancing:{region}:{account}:loadbalancer/app/{lbName}/{hash}
- ALB LoadBalancer dimension: app/{lbName}/{hash}
*/
const lbName = lb.loadBalancerArn.split(":").slice(-1)[0].replace(/^loadbalancer\//, '')
const dash = new Dashboard(scope, `dash`, {dashProps}).add(
  new cw.GraphWidget({
      height: 6,
      width: 6,
      title: "Requests by LB",
      left: [
        new Metric({
          namespace: "AWS/ApplicationELB",
          metricName: "RequestCount",
          dimensions: {
            "LoadBalancer": lbName
          }
        })
      ]
  })
)
```

**Expected behavior**
- expected output: 
  - `lbName = app/{lbName}/{hash}` 
- actual output
  - `lbName = arn:aws:elasticloadbalancing:{region}:{account}:loadbalancer/app/{lbName}/{hash}`
- actual template output
```yaml
dash73793BCC:
  Type: AWS::CloudWatch::Dashboard
  Properties:
    DashboardBody:
      Fn::Join:
        - ""
        - - '{"periodOverride":"auto","widgets":[{"type":"metric","width":6,"height":6,"x":0,"y":0,"properties":{"view":"timeSeries","title":"Requests
            by LB","region":"'
          - Ref: AWS::Region
          - '","metrics":[["AWS/ApplicationELB","RequestCount","LoadBalancer","'
          - Ref: lbA35910C5
          - '",{"yAxis":"left","period":300,"stat":"Average"}]],"annotations":{"horizontal":[]},"yAxis":{}}}]}'
  Metadata:
    aws:cdk:path: TestStack/dash/Resource

lbA35910C5:
  Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  Properties:
    ...
```

Currently, my workaround is using cloudformation intrinsic functions like the following:

```typescript
const tmp = Fn.split('/', Fn.select(5, Fn.split(":", lb.loadBalancerArn)))
const lbName = Fn.join('/', [Fn.select(1, tmp), Fn.select(2, tmp), Fn.select(3, tmp)])
```

Would be nice to be able to do this natively in typescript. Is this the expected behavior? If so, would +1 feature request to auto convert string functions into Fn.* calls where possible. If not, would love to see an error/warning or documentation about this behavior.

**Version:**
 - OS: mac
 - Programming Language: Typescript
 - CDK Version: 0.33
