### ISSUE TITLE
transitGatewayID in @aws-cdk/aws-ec2 not creating in Ref! in synth template

### ISSUE THREAD

**Issue by izaytsev** [awslabs/aws-cdk#3189]
* **I'm submitting a**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

The ec2.CfnTransitGatewayAttachment has a property TransitGatewayId. While the object resolves to the correct logical ID, the correct Ref element is not being generated by synth resulting in "TransitGatewayId: TransitGateway" and a rollback. 

```typescript
const TransitGateway = new ec2.CfnTransitGateway(this, 'Transit_Gateway', {
      description: "Transit Gateway",
      vpnEcmpSupport: 'enable',
      defaultRouteTableAssociation: 'enable',
      defaultRouteTablePropagation: 'enable',
      tags: [{ key: 'Name', value: "Transit Gateway" }],
    });

const TransitGatewayAttachmentEgress = new ec2.CfnTransitGatewayAttachment(this, 'TransitGatewayAttachmentEgress', {
      transitGatewayId: TransitGateway.logicalId,
      vpcId: egressVPC.vpcId,
      subnetIds: [egressVPC.privateSubnets[0].subnetId, egressVPC.privateSubnets[1].subnetId],
      tags: [{ key: 'Name', value: "TG-Egress-Private_SubNet-Attachment"}],
    });
    TransitGatewayAttachmentEgress.addDependsOn(TransitGateway);
```

* **What is the expected behavior (or behavior of feature suggested)?**
I receive a ref element for the transit gateway logical ID

* **What is the motivation / use case for changing the behavior or adding this feature?**
Fix missing Ref element for TransitGatewayId:

```yaml
TransitGatewayAttachmentEgress:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      SubnetIds:
        - Ref: EgressVPCPriavteEgressVPCSubNetSubnet1Subnet9F809618
        - Ref: EgressVPCPriavteEgressVPCSubNetSubnet2SubnetBE3E19B4
      TransitGatewayId: TransitGateway
      VpcId:
        Ref: EgressVPC08D3162E
      Tags:
        - Key: Name
          Value: TG-Egress-Private_SubNet-Attachment
    DependsOn:
      - TransitGateway
```

* **Please tell us about your environment:**
  
  - CDK CLI Version: "@aws-cdk/core": "^0.36.0",
  - Module Version: "@aws-cdk/aws-ec2": "^0.36.0"
  - OS: [OSX Mojave]
  - Language: [TypeScript]
