### ISSUE TITLE
`cdk ls -l` silently hangs when no default profile

### ISSUE THREAD

**Issue by 0xdevalias** [awslabs/aws-cdk#702]
When attempting to call `cdk ls -l` on a freshly init'd stack, with no default credentials, the program silently hangs.

When repeating the request explicitly passing in my profile, it works as expected:

```
⇒  cdk --profile devalias ls -l
-
    name: PocAwsCdkStack
    environment:
        name: 123456789012/ap-southeast-2
        account: '123456789012'
        region: ap-southeast-2
```

I would expect it display some form of descriptive error.
