### ISSUE TITLE
Logging property not present on creating a Cloudfront distribution using construct

### ISSUE THREAD

**Issue by amitsha** [awslabs/aws-cdk#721]
I've tried passing in an empty object for log bucket as well as an S3 Bucket, but the template generated by cdk doesn't have the Logging property.
```
new cfront.CloudFrontWebDistribution(
            this.props.stack,
            'CFWebDistribution',
            {
                originConfigs: [
                    {
                        s3OriginSource: {
                            s3BucketSource: this.props.originBucket,
                            originAccessIdentity: this.props.originAccessIdentity
                        },
                        behaviors: [{ isDefaultBehavior: true }]
                    }
                ],
                loggingConfig: {}
            }
        );
```
```
new cfront.CloudFrontWebDistribution(
            this.props.stack,
            'CFWebDistribution',
            {
                originConfigs: [
                    {
                        s3OriginSource: {
                            s3BucketSource: this.props.originBucket,
                            originAccessIdentity: this.props.originAccessIdentity
                        },
                        behaviors: [{ isDefaultBehavior: true }]
                    }
                ],
                loggingConfig: {
                    bucket: this.props.logsBucket   
                }
            }
        );
```
I'm generating the template using cdk sdk (stack.toCloudformation()). This seems to be a bug.

**Comment by eladb** [comment]
Indeed seems like a bug. [loggingConfig](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudfront/lib/web_distribution.ts#L382) is not being consulted when defining the underlying resource.

**Comment by ivawzh** [comment]
Hi. Not sure if it's related. CDK seems ignored my CDN logging config. Or am I doing something wrong: 

```ts
    this.cdn = new CloudFrontWebDistribution(this, 'CDN', {
      loggingConfig: {
        bucket: this.cdnLogS3,
        includeCookies: false,
      },
      ...
    }

    this.cdnLogS3 = new Bucket(this, 'CdnLogS3', {
      bucketName: (`x-cdn-log-y-z`),
      removalPolicy: RemovalPolicy.DESTROY,
      accessControl: BucketAccessControl.PRIVATE,
      publicReadAccess: false,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
    })
```

Output template:

```yaml
  CDNCFDistribution5C555532
        Logging:
          Bucket:
            Fn::GetAtt:
              - CDNLoggingBucket1EA6F0BF
              - RegionalDomainName
          IncludeCookies: false

  CDNLoggingBucket1EA6F0BF:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: stack/CDN/LoggingBucket/Resource

  CdnLogS345E0DDC6:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: x-cdn-log-y-z
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: stack/CdnLogS3/Resource
```
