### ISSUE TITLE
dotnet: Tagging an EC2 instance using L1 class doesn't work

### ISSUE THREAD

**Issue by ChintanRaval** [awslabs/aws-cdk#746]
I'm trying to bring up an EC2 instance while tagging the same with a few key/value pairs and this seems to be not working in .NET. 

I posted the issue with code samples in [StackOverflow](https://stackoverflow.com/questions/52399346/net-tagging-an-ec2-instance-using-aws-cdk-for-nets-low-level-cloudformation). Since I didn't get any traction on it, I [reached out](https://gitter.im/awslabs/aws-cdk?at=5ba2cf815df5194734e477a2) to the [aws-cdk channel](https://gitter.im/awslabs/aws-cdk) on Gitter and got help with [confirmation](https://gitter.im/awslabs/aws-cdk?at=5ba2d34b1ee2ca65023fa57e) that the same works when using `typescript` and therefore, I think this may be an issue _at least with .NET_.

Anyway, here's the code samples of what does and does not work.

### Does work
Thanks to @moofish32 & @ccurrie-amzn! 
#### Code
```typescript
class InstanceStack extends cdk.Stack {

    constructor(parent: cdk.App, id: string, props: {}) {
        super(parent, id, props);
        new ec2.cloudformation.InstanceResource(this, 'Instance', {
            imageId: "ami-0f1155cc2cb6b0cfd", // Microsoft Windows Server 2016 Base
            instanceType: "t2.micro",
            tags: [{key: 'foo', value: 'bar'}]
        });

    }
}
```
#### Result CF template 
```yaml
 Resources:
    Instance:
        Type: 'AWS::EC2::Instance'
        Properties:
            ImageId: ami-0f1155cc2cb6b0cfd
            InstanceType: t2.micro
            Tags:
                -
                    Key: foo
                    Value: bar
    CDKMetadata:
        Type: 'AWS::CDK::Metadata'
        Properties:
            Modules: '@aws-cdk/aws-ec2=0.9.1,@aws-cdk/cdk=0.9.1,@aws-cdk/cx-api=0.9.1,js-base64=2.4.9,vpc-examples=0.1.0'
```

#### Code
```c#
    public class TestStack : Amazon.CDK.Stack
    {
        public TestStack(Amazon.CDK.App parent, string name, Amazon.CDK.IStackProps props) : base(parent, name, props)
        {
            new Amazon.CDK.AWS.EC2.cloudformation.InstanceResource_(
                this, 
                "testInstance1", 
                new Amazon.CDK.AWS.EC2.cloudformation.InstanceResourceProps
                {
                    ImageId = "ami-0f1155cc2cb6b0cfd", // Microsoft Windows Server 2016 Base
                    InstanceType = "t2.micro",
                    Tags = new []
                    {
                        new Amazon.CDK.Tag { Key = "foo", Value = "bar" }
                    }
                });
        }
    }
```
#### Result CF template
```yaml
Resources:
    testInstance1:
        Type: 'AWS::EC2::Instance'
        Properties:
            ImageId: ami-0f1155cc2cb6b0cfd
            InstanceType: t2.micro
    CDKMetadata:
        Type: 'AWS::CDK::Metadata'
        Properties:
            Modules: '@aws-cdk/aws-ec2=0.9.1,@aws-cdk/aws-iam=0.9.1,@aws-cdk/cdk=0.9.1,@aws-cdk/cx-api=0.9.1,js-base64=2.4.9'
```
