### ISSUE TITLE
dotnet: Unable to set environment variables on FunctionResourceProps

### ISSUE THREAD

**Issue by patoncrispy** [awslabs/aws-cdk#762]
I'm having an issue creating a `FunctionResource_` in C#. The error I get is `Cannot set property ref of [object Object] which has only a getter`. It happens when trying to assign `FunctionResourceProps.Environment.Variables`:

```
var functionResourceProps = new FunctionResourceProps
            {
                ...
                Environment = new
                {
                    Variables = new Dictionary<string, string>
                    {
                        { "stage", "development"},
                    }
                }
            };

            var function = new FunctionResource_(this, "myfunction", functionResourceProps);
```

I'm using this to try and replicate an `AWS::Serverless::Function` resource I have already configured using SAM and the VS Toolkit.

Stack trace:

```
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at project.MyStack..ctor(App parent, String name, IStackProps props) in C:\code\project\MyStack.cs:line 37
   at project.Program.Main(String[] args) in C:\code\project\Program.cs:line 39
```

**Comment by patoncrispy** [comment]
An update on this. It actually doesn't matter how I set up my `FunctionResourceProps`, this error still occurs. The Environment variables was a red herring.

`var function = new FunctionResource_(this, "myfunction", new FunctionResourceProps());` will have the same result.

**Comment by eladb** [comment]
@costleya can you look into this please?

**Comment by costleya** [comment]
Is this still an issue?

I wrote the following code:
```csharp
using System.Collections.Generic;
using Amazon.CDK;
using Amazon.CDK.AWS.IAM;
using Amazon.CDK.AWS.Lambda;
using Amazon.CDK.AWS.Lambda.cloudformation;
using Amazon.CDK.AWS.Lambda.CfnFunction;

namespace aws_cdk_762
{
    class TestStack : Stack
    {
        public TestStack(App parent, string name, IStackProps props) : base(parent, name, props)
        {
            var role = new Role(this, "TestRole", new RoleProps
            {
                AssumedBy = new ServicePrincipal("lambda.amazonaws.com")
            });
            role.AddToPolicy(new PolicyStatement(PolicyStatementEffect.Allow)
                .AddAllResources()
                .AddAction("lambda:InvokeFunction"));

            new FunctionResource_(this, "myFunction", new FunctionResourceProps
            {
                Environment = new EnvironmentProperty
                {
                    Variables = new Dictionary<string, string>
                    {
                        {"stage", "development"}
                    }
                },
                Code = new InlineCode(""),
                Handler = "",
                Runtime = Runtime.Python37.Name,
                Role = role.RoleArn
            });
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var app = new App();
            new TestStack(app, "TestStack", new StackProps());
            app.Run();
        }
    }
}
```

Which gave me the output:
```yaml
Resources:
  TestRole6C9272DF:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: TestStack/TestRole/Resource
  TestRoleDefaultPolicyD1C92014:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: TestRoleDefaultPolicyD1C92014
      Roles:
        - Ref: TestRole6C9272DF
    Metadata:
      aws:cdk:path: TestStack/TestRole/DefaultPolicy/Resource
  myFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        {}
      Handler: ""
      Role:
        Fn::GetAtt:
          - TestRole6C9272DF
          - Arn
      Runtime: python3.7
      Environment:
        Variables:
          stage: development
    Metadata:
      aws:cdk:path: TestStack/myFunction
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.21.0,@aws-cdk/assets=0.21.0,@aws-cdk/aws-autoscaling-api=0.21.0,@aws-cdk/aws-cloudwatch=0.21.0,@aws-cdk/aws-codepipeline-api=0.21.0,@aws-cdk/aws-ec2=0.21.0,@aws-cdk/aws-events=0.21.0,@aws-cdk/aws-iam=0.21.0,@aws-cdk/aws-kms=0.21.0,@aws-cdk/aws-lambda=0.21.0,@aws-cdk/aws-logs=0.21.0,@aws-cdk/aws-s3=0.21.0,@aws-cdk/aws-s3-notifications=0.21.0,@aws-cdk/aws-sqs=0.21.0,@aws-cdk/aws-stepfunctions=0.21.0,@aws-cdk/cdk=0.21.0,@aws-cdk/cx-api=0.21.0,jsii-runtime=DotNet/4.0.30319.42000
```
