### ISSUE TITLE
VPCEndpointType doesn't exist

### ISSUE THREAD

**Issue by mscharley** [awslabs/aws-cdk#765]
I'm using CDK 0.9.2.

The following is being generated:

```
    DatabasesEndpointECB50BE6:
        Type: 'AWS::EC2::VPCEndpoint'
        Properties:
            ServiceName:
                'Fn::Sub':
                    - 'com.amazonaws.${region}.dynamodb'
                    -
                        region:
                            Ref: 'AWS::Region'
            VpcId:
                Ref: Vpc
            PolicyDocument:
                Statement:
                    -
                        Action:
                            - 'dynamodb:Batch*'
                            - 'dynamodb:Delete*'
                            - 'dynamodb:DescribeTable'
                            - 'dynamodb:GetItem'
                            - 'dynamodb:PutItem'
                            - 'dynamodb:Update*'
                        Effect: Allow
                        Principal: '*'
                        Resource:
                            'Fn::Sub':
                                - 'arn:aws:dynamodb:${region}:${account}:table/${prefix}.*'
                                -
                                    account:
                                        Ref: 'AWS::AccountId'
                                    prefix:
                                        Ref: TablePrefix
                                    region:
                                        Ref: 'AWS::Region'
                        Sid: AccessToSpecificTable
            RouteTableIds:
                -
                    Ref: VpcPrivateSubnet1RouteTableB2C5B500
                -
                    Ref: VpcPrivateSubnet2RouteTableA678073B
            VPCEndpointType: Gateway
```

Which is almost correct. The last property is actually called `VpcEndpointType` according to the documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html

If I manually update the property name in a synthed template before manually deploying to CloudFormation then the template works.
