### ISSUE TITLE
dotnet: Error importing existing Vpc

### ISSUE THREAD

**Issue by indikaudagedara** [awslabs/aws-cdk#816]
I'm trying to import an existing Vpc into a `dotnet` cdk stack using the example [here](https://github.com/awslabs/aws-cdk/issues/506) provided by @eladb 

```          
            var vpc = VpcNetworkRef.Import(this, "ExternalVpc", new VpcNetworkRefProps
            {
                VpcId = "vpc-ff",
                AvailabilityZones = new AvailabilityZoneProvider(this).AvailabilityZones,
                PrivateSubnetIds = new[] {"subnet-0xx", "subnet-0yy", "subnet-0zz"},
                PublicSubnetIds = new[] {"subnet-aa", "subnet-bb", "subnet-cc"}
            });
```

However, when I do `cdk deploy` it says
```
Unhandled Exception: System.MemberAccessException: Cannot create an instance of Amazon.CDK.AWS.EC2.VpcNetworkRef because it is an abstract class.
   at System.Reflection.RuntimeConstructorInfo.CheckCanCreateInstance(Type declaringType, Boolean isVarArg)
   at System.Reflection.RuntimeConstructorInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.JSII.Runtime.Services.ReferenceMap.GetOrCreateNativeReference(ByRefValue byRefValue)
   at Amazon.JSII.Runtime.Services.Converters.JsiiToFrameworkConverter.TryConvertClass(IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertCustomType(IReferenceMap referenceMap, Object value, Boolean isOptional, String fullyQualifiedName, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(TypeReference typeReference, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeStaticMethod[T](Type type, Object[] arguments, String methodName)
   at Stack.AppStack..ctor(App parent, String name, IStackProps props) in E:\Stack\AppStack.cs:line 13
```

Is this a bug? Or is there another way to import an existing Vpc? (on a side note why [is it required to](https://gist.github.com/mipearson/aeaf303b0770c25f8b5f6e360594cfbf) specify all the properties and not just the `VpcId`?)

**Comment by rix0rrr** [comment]
Duplicate of https://github.com/awslabs/jsii/issues/223. @costleya, is the fix released yet, and if so, what version of what tool should be installed?

**Comment by eladb** [comment]
Coming up in jsii-0.7.7

**Comment by indikaudagedara** [comment]
With ` jsii-0.7.7` the error ` Cannot create an instance of Amazon.CDK.AWS.EC2.VpcNetworkRef because it is an abstract class.` seems to be gone but now getting a different error

```
            var vpc = VpcNetworkRef.Import(this, "ExternalVpc", new VpcNetworkRefProps
            {
                VpcId = "vpc-3f0a6758",
                AvailabilityZones = new [] {"ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c" },
                PrivateSubnetIds = new[]
                    {"subnet-07a29232a40c5b7c3", "subnet-087d4e011854270fd", "subnet-08d59b2790f41f7fe"},
                PublicSubnetIds = new[] {"subnet-59207e3e", "subnet-7c66ac24", "subnet-8ac78fc3" }
            });

            Console.WriteLine($"VpcId = {vpc?.VpcId}");
            
            var lambdaSecurityGroup = new SecurityGroup(this, "LambdaSecurityGroup", new SecurityGroupProps
            {
                Description = "Enable lambda access to Vpc resources",
                Vpc = vpc,
                GroupName = "LambdaSecurityGroup"
            });
```

Looks like it imports the Vpc, but when creating a security group attached to it throws 

```
VpcId = vpc-3f0a6758

Unhandled Exception: Amazon.JSII.Runtime.JsiiException: Cannot read property 'vpcId' of undefined
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at ....AppStack..ctor(App parent, String name, IStackProps props) in ...\AppStack.cs:line 28
```

Any idea what's going wrong?

**Comment by costleya** [comment]
Is this still an issue?

I wrote the following bootstrap code, and copied in the code you provided.
```csharp
using System;
using Amazon.CDK;
using Amazon.CDK.AWS.EC2;

namespace aws_cdk_816
{
    class TestStack : Stack
    {
        public TestStack(App app, string name, IStackProps stackProps) : base(app, name, stackProps)
        {
            var vpc = VpcNetworkRef.Import(this, "ExternalVpc", new VpcNetworkRefProps
            {
                VpcId = "vpc-3f0a6758",
                AvailabilityZones = new[] {"ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"},
                PrivateSubnetIds = new[]
                    {"subnet-07a29232a40c5b7c3", "subnet-087d4e011854270fd", "subnet-08d59b2790f41f7fe"},
                PublicSubnetIds = new[] {"subnet-59207e3e", "subnet-7c66ac24", "subnet-8ac78fc3"}
            });

            Console.WriteLine($"VpcId = {vpc?.VpcId}");

            new SecurityGroup(this, "LambdaSecurityGroup", new SecurityGroupProps
            {
                Description = "Enable lambda access to Vpc resources",
                Vpc = vpc,
                GroupName = "LambdaSecurityGroup"
            });
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var app = new App();
            new TestStack(app, "TestStack", new StackProps());
            app.Run();
        }
    }
}
```

Which ran successfully, giving the following output:
```yaml
VpcId = vpc-3f0a6758
Resources:
  LambdaSecurityGroup0BD9FC99:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable lambda access to Vpc resources
      GroupName: LambdaSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        []
      VpcId: vpc-3f0a6758
    Metadata:
      aws:cdk:path: TestStack/LambdaSecurityGroup/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.21.0,@aws-cdk/aws-ec2=0.21.0,@aws-cdk/aws-iam=0.21.0,@aws-cdk/cdk=0.21.0,@aws-cdk/cx-api=0.21.0,jsii-runtime=DotNet/4.0.30319.42000
```

I am using .NET Core 2.2 and CDK version 0.21.0.
