### ISSUE TITLE
Cannot specify "ON" as a property value

### ISSUE THREAD

**Issue by lusentis** [awslabs/aws-cdk#875]
Hello, I was trying to create a Cognito User Pool, using the CloudFormation construct, with the following code:

```js
    new UserPoolResource(this, "adminUserPool", {
      adminCreateUserConfig: {
        allowAdminCreateUserOnly: true,
      },
      autoVerifiedAttributes: ["email", "phone_number"],
      deviceConfiguration: {
        challengeRequiredOnNewDevice: true,
        deviceOnlyRememberedOnUserPrompt: true,
      },
      mfaConfiguration: "ON",
      policies: {
        passwordPolicy: {
          minimumLength: 99,
          requireLowercase: true,
          requireNumbers: true,
          requireSymbols: true,
          requireUppercase: true,
        },
      },
      usernameAttributes: ["email"],
    });
```

The problem I encountered is, if I specify `mfaConfiguration` as "ON", the generated YAML will be something like:

```yaml
...
                ChallengeRequiredOnNewDevice: true
                DeviceOnlyRememberedOnUserPrompt: true
            MfaConfiguration: ON
            Policies:
...
```

And, as in YAML, the literal ON is an alias for true... the CloudFormation stack deploy fails with this error: `1 validation error detected: Value 'true' at 'mfaConfiguration' failed to satisfy constraint: Member must satisfy enum value set: [OPTIONAL, OFF, ON]`.

I was not able to find a way to "escape" this ON literal - wrapping it in "" or '' should be enough.
