### ISSUE TITLE
dotnet: RestApi ignores StageName

### ISSUE THREAD

**Issue by indikaudagedara** [awslabs/aws-cdk#892]
I have a `RestApi` as following with a custom stage name (`v1`)

```
            var api = new RestApi(this, "MyApi-Dev", new RestApiProps
            {
                RestApiName = "MyApi-Dev",
                DeployOptions = new StageOptions()
                {
                    StageName = "v1",
                }
            });
```

However, the synthesized stage name is always `prod`

```
    OpenpayWebApiDevDeployment818343587d93c016b2e8b8b472dee514947dea9b:
        Type: 'AWS::ApiGateway::Deployment'
        Properties:
            RestApiId:
                Ref: MyApiDevF64B856A
            Description: 'Automatically created by the RestApi construct'
        DependsOn:
            - MyApiDevDiagnostics448AC7CB
            -MyApiDevDiagnosticsANY23721B90
    OpenpayWebApiDevDeploymentStageprodF2337B1C:
        Type: 'AWS::ApiGateway::Stage'
        Properties:
            RestApiId:
                Ref: MyApiDevF64B856A
            DeploymentId:
                Ref: MyApiDeployment818343587d93c016b2e8b8b472dee514947dea9b
            StageName: prod
```

**Comment by eladb** [comment]
This seems like a .NET bindings issue. A typescript version of this works, but I managed to reproduce this with .NET. @costleya, can you please take a look? I am curious what's going on here...

**Comment by eladb** [comment]
@costleya any chance you can take a look at this soon?

**Comment by costleya** [comment]
Is this still an issue?

I wrote the following code, using the snippet you provided:
```csharp
using Amazon.CDK;
using Amazon.CDK.AWS.APIGateway;
using ResourceOptions = Amazon.CDK.AWS.APIGateway.ResourceOptions;

namespace aws_cdk_892
{
    class TestStack : Stack
    {
        public TestStack(App parent, string name, IStackProps stackProps) : base(parent, name, stackProps)
        {
            var api = new RestApi(this, "MyApi-Dev", new RestApiProps()
            {
                RestApiName = "MyApi-Dev",
                DeployOptions = new StageOptions
                {
                    StageName = "v1"
                }
            });

            var books = api.Root.AddResource("books", new ResourceOptions());
            books.AddMethod("GET", new MockIntegration(new IntegrationOptions()), new MethodOptions());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var app = new App();
            new TestStack(app, "TestStack", new StackProps());
            app.Run();
        }
    }
}
```

Which produced the following output:
```yaml
Resources:
  MyApiDev909C0079:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: HEADER
      Name: MyApi-Dev
    Metadata:
      aws:cdk:path: TestStack/MyApi-Dev/Resource
  MyApiDevDeployment895CA66E621cad007d3e2e473771230aa3ab7e86:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: MyApiDev909C0079
      Description: Automatically created by the RestApi construct
    DependsOn:
      - MyApiDevbooksBB1ABC47
      - MyApiDevbooksGET66BFFADB
    Metadata:
      aws:cdk:path: TestStack/MyApi-Dev/Deployment/Resource
  MyApiDevDeploymentStagev1771DC271:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: MyApiDev909C0079
      DeploymentId:
        Ref: MyApiDevDeployment895CA66E621cad007d3e2e473771230aa3ab7e86
      MethodSettings:
        - HttpMethod: "*"
          LoggingLevel: "OFF"
          ResourcePath: /*
      StageName: v1
    Metadata:
      aws:cdk:path: TestStack/MyApi-Dev/DeploymentStage.v1/Resource
  MyApiDevCloudWatchRole37E4AF7F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: TestStack/MyApi-Dev/CloudWatchRole/Resource
  MyApiDevAccountC2376201:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - MyApiDevCloudWatchRole37E4AF7F
          - Arn
    DependsOn:
      - MyApiDev909C0079
    Metadata:
      aws:cdk:path: TestStack/MyApi-Dev/Account
  MyApiDevbooksBB1ABC47:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - MyApiDev909C0079
          - RootResourceId
      PathPart: books
      RestApiId:
        Ref: MyApiDev909C0079
    Metadata:
      aws:cdk:path: TestStack/MyApi-Dev/books/Resource
  MyApiDevbooksGET66BFFADB:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: MyApiDevbooksBB1ABC47
      RestApiId:
        Ref: MyApiDev909C0079
      AuthorizationType: NONE
      Integration:
        ContentHandling: CONVERT_TO_BINARY
        PassthroughBehavior: WHEN_NO_MATCH
        Type: MOCK
    Metadata:
      aws:cdk:path: TestStack/MyApi-Dev/books/GET/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.21.0,@aws-cdk/assets=0.21.0,@aws-cdk/aws-apigateway=0.21.0,@aws-cdk/aws-autoscaling-api=0.21.0,@aws-cdk/aws-cloudwatch=0.21.0,@aws-cdk/aws-codepipeline-api=0.21.0,@aws-cdk/aws-ec2=0.21.0,@aws-cdk/aws-events=0.21.0,@aws-cdk/aws-iam=0.21.0,@aws-cdk/aws-kms=0.21.0,@aws-cdk/aws-lambda=0.21.0,@aws-cdk/aws-logs=0.21.0,@aws-cdk/aws-s3=0.21.0,@aws-cdk/aws-s3-notifications=0.21.0,@aws-cdk/aws-sqs=0.21.0,@aws-cdk/aws-stepfunctions=0.21.0,@aws-cdk/cdk=0.21.0,@aws-cdk/cx-api=0.21.0,jsii-runtime=DotNet/4.0.30319.42000
Outputs:
  MyApiDevEndpointCB89BD0A:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: MyApiDev909C0079
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - Ref: MyApiDevDeploymentStagev1771DC271
          - /
    Export:
      Name: TestStack:MyApiDevEndpointCB89BD0A
```

Which has ```StageName: v1```, as expected.

I am using .NET Core 2.2 with CDK version 0.21.0.
