### ISSUE TITLE
No AWS Tagging Support on Stacks themselves

### ISSUE THREAD

**Issue by lestephane** [awslabs/aws-cdk#932]
When I saw in another issue that tag propagation was added, my first instinct
was to try to set tags on the software.amazon.awscdk.App (not possible, 
does not implement ITaggable, at least in java), then i tried to set tags on the
software.amazon.awscdk.Stack  (same problem). 

My use case is to (1) add tags on the App level with propagation, that (2) will be
set in all the AWS::CloudFormation::Stack resources created by cdk deploy, and
in turn (3) will be set on all the resources created within said stacks.

I tried implementing ITaggable on my App subclass and my Stack subclass.
The tags get passed and set all the way to the resources all right, so that's (1) and (3) covered.
But what about (2)? If I understand the design correctly, you're completely reliant
on changesets, and the tags for the Stacks cannot be passed in the stack template.
They would have to be passed in the api call to createChangeSet:

# deploy-stack.ts
```typescript
  const changeSet = await cfn.createChangeSet({
    StackName: deployName,
    ChangeSetName: changeSetName,
    ChangeSetType: update ? 'UPDATE' : 'CREATE',
    Description: `CDK Changeset for execution ${executionId}`,
    TemplateBody: bodyParameter.TemplateBody,
    TemplateURL: bodyParameter.TemplateURL,
    Parameters: params,
    Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM' ]
    # ADD TAGS SOMEWHERE HERE?
  }).promise();
```

Makes sense?

**Comment by rafcio19** [comment]
Tagging stacks would be very useful, it's supported by virtually all other CF deployment tools :)

**Comment by eladb** [comment]
Thanks to the awesome work contributed by @moofish32, this is naturally supported using aspects.

Here is a python version (my new favorite way to use the CDK):

```py
from aws_cdk import cdk
from aws_cdk import aws_sqs
from aws_cdk import aws_dynamodb


class MyStack(cdk.Stack):
    def __init__(self, scope: cdk.Construct, cid: str, **kwargs) -> None:
        super().__init__(scope, cid, **kwargs)

        aws_sqs.Queue(self, 'MyQueue')
        aws_dynamodb.Table(self, 'MyTable',
                           partition_key=aws_dynamodb.Attribute(
                               name='id',
                               type=aws_dynamodb.AttributeType.String))


app = cdk.App()

stack = MyStack(app, 'stack1', stack_name='first-python-app')
stack.node.apply(cdk.Tag('Foo', 'Bar'))

app.run()
```

In TypeScript:

```ts
stack.node.apply(new cdk.Tag('Foo', 'Bar'));
```

The result:

```yaml
Resources:
  MyQueueE6CA6235:
    Type: AWS::SQS::Queue
    Properties:
      Tags:
        - Key: Foo
          Value: Bar
  MyTable794EDED1:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Foo
          Value: Bar
```
